//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxInfo
    {
        public BoxInfo()
        {
            this.ShipmentInfors = new HashSet<ShipmentInfor>();
            this.ShipmentOuts = new HashSet<ShipmentOut>();
            this.ShipmentInforTemps = new HashSet<ShipmentInforTemp>();
            this.ShipmentOutTemps = new HashSet<ShipmentOutTemp>();
        }
    
        public int Id { get; set; }
        public string BoxId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ShipmentQuantity { get; set; }
        public Nullable<int> MasterBillId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<ShipmentInfor> ShipmentInfors { get; set; }
        public virtual ICollection<ShipmentOut> ShipmentOuts { get; set; }
        public virtual MasterBill MasterBill { get; set; }
        public virtual ICollection<ShipmentInforTemp> ShipmentInforTemps { get; set; }
        public virtual ICollection<ShipmentOutTemp> ShipmentOutTemps { get; set; }
    }
}
