//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_profile
    {
        public Business_profile()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Tax { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Company { get; set; }
        public string Branch { get; set; }
        public Nullable<int> SaleId { get; set; }
        public string short_name { get; set; }
        public string type { get; set; }
        public string contract { get; set; }
        public string RefCode { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
