//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manifest
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string MasterAirWayBill { get; set; }
        public string ShipmentNo { get; set; }
        public string FlightNumber { get; set; }
        public string FlightDate { get; set; }
        public string BoxID { get; set; }
        public string HSCode { get; set; }
        public string ContactName { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string Currency { get; set; }
        public string Content { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Original { get; set; }
        public string Destination { get; set; }
        public string Country { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string DeclarationNo { get; set; }
    }
}
