//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentOutTemp
    {
        public string ShipmentId { get; set; }
        public Nullable<int> BoxIdRef { get; set; }
        public string BoxIdString { get; set; }
        public Nullable<int> MasterBillId { get; set; }
        public string MasterBillIdString { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
    
        public virtual BoxInfo BoxInfo { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual MasterBill MasterBill { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
