//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Warehouse()
        {
            this.Employees = new HashSet<Employee>();
            this.ShipmentInfors = new HashSet<ShipmentInfor>();
            this.ShipmentInforTemps = new HashSet<ShipmentInforTemp>();
            this.ShipmentOuts = new HashSet<ShipmentOut>();
            this.ShipmentOutTemps = new HashSet<ShipmentOutTemp>();
        }
    
        public int Id { get; set; }
        public string IdCode { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<ShipmentInfor> ShipmentInfors { get; set; }
        public virtual ICollection<ShipmentInforTemp> ShipmentInforTemps { get; set; }
        public virtual ICollection<ShipmentOut> ShipmentOuts { get; set; }
        public virtual ICollection<ShipmentOutTemp> ShipmentOutTemps { get; set; }
    }
}
